---
title: "Tree Aggregation"
author: 
- name: Ruizhu HUANG
  affiliation: 
  - Institute of Molecular Life Sciences, University of Zurich.
  - SIB Swiss Institute of Bioinformatics.
- name: Charlotte Soneson
  affiliation: 
  - Institute of Molecular Life Sciences, University of Zurich.
  - SIB Swiss Institute of Bioinformatics.
- name: Mark Robinson
  affiliation: 
  - Institute of Molecular Life Sciences, University of Zurich.
  - SIB Swiss Institute of Bioinformatics.
package: treeAGG
output: 
  BiocStyle::html_document
vignette: >
  %\VignetteIndexEntry{Tree Aggregation}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
bibliography: treeAGG_vignette.bib
---




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```
# Introduction

The arrangement of hypotheses in a hierarchical structure appears in many research fields and often indicates different resolutions at which data can be viewed. On which resolution level should the signal be intepreted has arisen researchers' interest. For example, the association between a phenotypic outcome (e.g., diseased and healthy) and abundance changes of entities (e.g., microbes or cells) might be of interest. However, the abundance change on the entity level might not be evident due to the low abundance even though it does exist. It might become evident at a higher hierarchical level, which represents a cluster of entities, due to the accumulation caused by the similarity in response to the environment shared by the entities in the same cluster. 

On which hierarchical level should the change be tested becomes a critical question to be answered. A flexible method to select hierarchical level, instead of cutting the tree structure at arbitary levels, is desired. Our package treeAGG, which uses the minP algorithm, is a such tool. It does a bottom-up search for the optimal level of a tree to interpret signal by integrating two types of data: abundance estimate of a set of entities (e.g., microbes or cells) across a set of samples (e.g., diseased and healthy) and a tree that encodes a hierarchical relationship among the entities (e.g., a phylogeny of microbes). It could flexibly combine with current available tools, such as edgeR or DESeq2.



# Method

Consider the case in which a count table and a tree of $n$ entities (e.g. microbes or cells) are available. The goal is to find the hierarchical level of the tree on which the association should be intepreted. Each row of the count table represents an entity $g$. Each column is a sample. Samples are collected from different conditions (e.g., healthy and diseased). Let $Y_{gi}$ denote the observed count of an entity (a leaf on the tree) or a cluster of entities (an internal node on the tree) $g$ in sample $i$. To investigate whether an entity or a cluster of entities has differential abundance under different conditions, currently available packages, such as, `r Biocpkg("edgeR")` and `r Biocpkg("DESeq2")`) could be used. Let's take `r Biocpkg("edgeR")` as an example and explain how our package works.

As assumed in `r Biocpkg("edgeR")`[@Robinson2009], $Y_{gi}$ follows a negative binomial distribution
$$\mathbf{Y}_{gi}  \sim NB(\mathbf{M}_{i}\mathbf{p}_{gj}, \mathbf{\phi}_{g})  $$
$$g = 1, 2, 3, ..., n, n+1, ..., n+K;$$ 
$$i = 1, 2, ... m;$$ 
$$j = 1, 2, ..., J.$$


Here,  $\mathbf{M}_{i}$ is the effective total count of sample $i$, $\mathbf{p}_{gj}$ is the relative abundance of OTU or internal node $g$ in experimental group (or condition) $j$ to which sample $i$ belongs, and $\mathbf{\phi}_{g}$ is the dispersion parameter used to consider the biological variation between samples. The negative binomial distribution is parameterized with mean as $\mathbb{E}[\mathbf{Y}_{gi}] = \mu_{gi} =  \mathbf{M}_{i}\mathbf{p}_{gj}$, and variance as
$\text{Var}[\mathbf{Y}_{gi}] = \mu_{gi}(1+\mu_{gi}\phi_{g})$. When $\mathbf{\phi}_{g} = 0$, the negative binomial distribution reduces to Poisson distribution. In total, we have $n$ entities, $K$ entity clusters, $m$ samples and $J$ conditions.

A generalized linear model could be built at each leaf (an entity) and each internal node (a cluster of entities) of the tree after the value of  $\mathbf{\phi}_{g}$ is estimated,
$$
\text{log}(\mu_{gi}) = \mathbf{x}^{T}_{i} \mathbf{\beta}_{g}, \quad g = 1, 2, ..., n, n+1, ...., n+K
$$
where $\mathbf{x}^{T}_{i}$ is a vector of covariates including confounders (e.g., age, gender) and the covariate of interest (e.g., diseased and healthy sample) applied on sample $i$, and $\mathbf{\beta}_{g}$ is a vector of corresponding regression coefficients. Let $\beta^{1}_{g}$ denote the coefficient value for the covariate of interest in $\beta_{g}$.


We arrange the hypotheses in a tree-like structure and test hypotheses
$$
H^{g}_{0}: \beta^{1}_{g} = 0, (g = 1, 2, ..., n, n+1, ...., n+K ),
$$
where n is the number of tree leaves and K is the number of internal nodes.

The min-P algorithm is implemented to do the tree aggregation as below.

* Test all hypotheses at tree leaves and internal nodes simultaneously and use Benjamin-Hochberg procedure to control the FDR rate.
* Start from the tree leaves. Compare the adjusted p value (or p value) on leaves to that on their parent node. If the minimum value is on the level parent node, take the parent node; otherwise, take the children and compare them to one higher level of their parent.
* Repeat the previous step until reach the root.

Finally, for any internal node in the final result, its descendants all have higher p value than it.





## References
