#' A simulated phylogenetic tree with 10 tips and 9 internal nodes
#'
#' A random phylo object created using the function \code{\link[ape]{rtree}}
#' @importFrom ape rtree
#' @format A phylo object with 10 tips and 9 internal nodes:
#' \describe{
#'   \item{Tip labels}{t1, t2, ..., t10.}
#'   \item{Node labels}{Node_11, Node_12, ..., Node_19}
#' }
#'
#'
"tinyTree"


#' A simulated phylogenetic tree with 50 tips and 49 internal nodes
#'
#' A random phylo object created using the function \code{\link[ape]{rtree}}
#' @importFrom ape rtree
#' @format A phylo object with 50 tips and 49 internal nodes:
#' \describe{
#'   \item{Tip labels}{t1, t2, ..., t50.}
#'   \item{Node labels}{NULL}
#' }
"exTree"


#' A simulated phylogenetic tree with 800 tips and 799 internal nodes
#'
#' A random phylo object created using the function \code{\link[ape]{rtree}}
#' @importFrom ape rtree
#' @format A phylo object with 800 tips and 799 internal nodes:
#' \describe{
#'   \item{Tip labels}{t1, t2, ..., t800.}
#'   \item{Node labels}{NULL}
#' }
"bigTree"

#' AML-sim data
#'
#' A semi-simulated count table generated by computationally "spiking in" small
#' percentages of AML blast cells into healthy BMMCs (created by Lukas Weber)
#'
#' @format A data frame of cell counts collected from healthy and
#'   cytogenetically normal (CN) samples:
#' \describe{
#'   \item{cluster}{The cluster labels}
#'   \item{p_vals}{The nominal p values}
#'   \item{p_adj}{The adjusted p values}
#'   \item{n_cells}{The number of cells in the clusters}
#'   \item{n_spikein}{The number of spike-in cells}
#'   \item{prop_spikein}{The proportion of spike-in cells}
#'   \item{true}{Whether the cluster is truly differential abundant}
#'   \item{healthy_H1}{The counts from the first healthy sample}
#'   \item{healthy_H2}{The counts from the second healthy sample}
#'   \item{healthy_H3}{The counts from the third healthy sample}
#'   \item{healthy_H4}{The counts from the forth healthy sample}
#'   \item{healthy_H5}{The counts from the fifth healthy sample}
#'   \item{CN_H1}{The counts from the first CN sample}
#'   \item{CN_H2}{The counts from the second CN sample}
#'   \item{CN_H3}{The counts from the third CN sample}
#'   \item{CN_H4}{The counts from the forth CN sample}
#'   \item{CN_H5}{The counts from the fifth CN sample}
#' }
"res_table"

#' Count table of the AML-sim data
#'
#' A semi-simulated count table generated by computationally "spiking in" small
#' percentages of AML blast cells into healthy BMMCs (created by Lukas Weber)
#'
#' @format A data frame of cell counts collected from healthy and
#'   cytogenetically normal (CN) samples:
#' \describe{
#'   \item{healthy_H1}{The counts from the first healthy sample}
#'   \item{healthy_H2}{The counts from the second healthy sample}
#'   \item{healthy_H3}{The counts from the third healthy sample}
#'   \item{healthy_H4}{The counts from the forth healthy sample}
#'   \item{healthy_H5}{The counts from the fifth healthy sample}
#'   \item{CN_H1}{The counts from the first CN sample}
#'   \item{CN_H2}{The counts from the second CN sample}
#'   \item{CN_H3}{The counts from the third CN sample}
#'   \item{CN_H4}{The counts from the forth CN sample}
#'   \item{CN_H5}{The counts from the fifth CN sample}
#' }
"cytofCount"

#' The information about clusters of the AML-sim data
#'
#' A data frame provides information about clusters. Each cluster corresponds to
#' a row in the \code{\link{cytofCount}}.
#'
#' @format A data frame of cluster information:
#' \describe{
#'   \item{cluster}{The name of cluster}
#'   \item{n_cells}{The number of cells in the cluster}
#'   \item{n_spikein}{The number of spike-in cells in the cluster}
#'   \item{prop_spikein}{The proportion of spike-in cells in the cluster}
#'   \item{truth}{whether the cluster is differential abundant between the healthy
#'   sample and the CN sample}
#' }
"cytof_cluster"

#' The information about samples of the AML-sim data
#'
#' A data frame provides information about samples. Each sample corresponds to
#' a column in the \code{\link{cytofCount}}.
#'
#' @format 5 samples are collected from 5 healthy subjects. Each sample is
#'   equally split into two subsamples, one of which spike in CN cells to
#'   simulate samples from patients.
#' \describe{
#'   \item{group}{The group that a sample collected from: healthy or CN.}
#'   \item{patient}{The patient that the sample collected from. }
#' }
"cytof_sample"

#' The true signal in the AML-sim data
#'
#' This data provides the differential abundance information of clusters in the
#' AML-sim data
#'
#' @format A data frame of two columns:
#' \describe{
#'   \item{cluster}{The cluster label}
#'    \item{true}{Whether the cluster is truly differential abundant}
#' }
"cytofTruth"

#' The hierarchical tree of the cells in the AML-sim data
#'
#' A hclust object which records the hierarchical structure of the cells in the
#' AML-sim data.
#'
#' @format A hclust object with 900 leaves. Each leaf is a cell cluster.
"cytofTree"



