#' update the value of contrast in treeSummarizedExperiment object
#'
#' \code{updateContrast} updates the output of \code{\link{runEdgeR}} when a
#' different contrast is specified. It conducts likelihood ratio test for a
#' given coefficient contrast by using the function \code{\link[edgeR]{glmLRT}}.
#'
#' @param data A treeSummarizedExperiment object. The output from
#'   \code{\link{runEdgeR}}.
#' @param contrast A numeric vector to define contrast.
#'
#' @importFrom edgeR glmLRT
#' @importFrom S4Vectors DataFrame
#' @export
#'
#' @return A treeSummarizedExperiment object. The overall structure is the same
#'   to the output of \code{\link{runEdgeR}}. The updates occur in the
#'   \code{assays} and the \code{contrast} (one element of \code{metadata}).
#' \item{assays}{It stores a list of tables extracted from a \code{DGELRT}
#' object that is generated by \code{\link[edgeR]{glmLRT}} with the specified
#' \code{contrast}}
#' \item{rowData}{It stores the information of rows in \code{assays} as input}
#' \item{colData}{NULL}
#' \item{metadata}{
#'    \itemize{
#'    \item \code{assaysInput} a list of matrix-like elements. Stay the same as
#'    the \code{assaysInput} in input \code{data}.
#'    \item \code{use.assays} a numeric vector. Stay the same as the
#'    \code{use.assays} in input \code{data}.
#'    \item \code{design} a design matrix. Stay the same as the \code{design} in
#'    input \code{data}.
#'    \item \code{contrast} the contrast vector as input.
#'    \item \code{dgeGLM} a list of \code{DGEGLM} objects. Stay the same as the
#'    \code{dgeGLM} in input \code{data}.
#'    }
#' }
#'
#' @seealso \code{\link{runEdgeR}} \code{\link[edgeR]{glmFit}}
#'   \code{\link[edgeR]{glmLRT}} \code{\link[edgeR]{DGEGLM-class}}
#' @author Ruizhu HUANG
#'
updateContrast <- function(data, contrast){

    # check whether glmFit exists in the metadata.
    metaD <- metadata(data)
    is.glmFit <- names(metaD) %in% "dgeGLM"
    if (!any(is.dgeGLM)) {
        stop("A DGEGLM object output from glmFit (edgeR) can not be found. \n ")
    }

    # check whether the non-null elements in dgeGLM are DGEGLM object
    gf <- metaD$dgeGLM
    use.gf <- metaD$use.assays
    is.DGEGLM <- lapply(use.gf, FUN = function(x){
        class(gf[[x]]) == "DGEGLM"
    })
    is.DGEGLM <- unlist(is.DGEGLM)
    if (!all(is.DGEGLM)) {
        stop("Wrong form in 'dgeGLM' of metadata: ", which(!is.DGEGLM),
             " is not DGEGLM")
    }

    # update result use the new contrast.
    fit <- metaD$dgeGLM
    lrt <- lapply(seq_along(fit), FUN = function(x) {
        if (x %in% use.assays) {
            glmLRT(fit[[x]], contrast = contrast)
        } else {
            NULL
        }
    })

    final <- lapply(lrt, FUN = function(x) { x$table })

    # output result to metadata
    outP <- lapply(seq_along(final), function(x) {

        if (x %in% use.assays) {
            # find rows deleted
            idx <- as.numeric(rownames(final[[x]]))
            idc <- setdiff(seq_len(nrow(obj)), idx)

            # add and rearrange rows so that the output is also row-wise
            # corresponding to the assays data.
            df <- DataFrame(final[[x]])
            dm <- matrix(NA, nrow = length(idc), ncol = ncol(df),
                         dimnames = list(idc, colnames(df)))
            dfc <- DataFrame(dm)
            dfA <- rbind(df, dfc)
            dfA <- dfA[order(as.numeric(rownames(dfA))),]
            return(dfA)
        } else {
            NULL
        }
    })
    names(outP) <- names(assays(data))

    # update contrast
    metaD$contrast <- contrast

    # update tse
    outL <- treeSummarizedExperiment(assays = outP,
                                     rowData = rowData(data),
                                     metadata = metaD,
                                     tree = treeData(data),
                                     linkData = linkData(data))

    return(outL)
}
